delivery/urls.py
from django.urls import path
from . import views

app_name="delivery"
urlpatterns = [
    path('add_res/', views.add_res, name='add_res'),
    path('veiw_menu/<int:id>/',views.view_menu, name="view_menu"),
    path('add_menu/',views.add_menu, name='add_menu'),
    path('delete_menu/<int:id>', views.delete_menu, name='delete_menu'),
    path('view_cusmenu/<int:id>/<str:username>/',views.view_cusmenu, name="view_cusmenu"),
    path('view_cart/<str:username>/', views.view_cart, name="view_cart"),
    path('add_to_cart/<int:menuid>/<str:username>/', views.add_to_cart, name="add_to_cart"),
    path('ordersucess/<str:username>', views.ordersucess, name="ordersucess"),
    path('orders/<str:username>',views.orders,name='view_orders'),
    path('edit_res/<int:id>', views.edit_res,name="edit_res"),
    path('delete_res/<int:id>', views.delete_res,name="delete_res"),
    path('edit_menu/<int:id>', views.edit_menu,name="edit_menu"),
    path('cart/quantity/<int:id>/<str:op>/', views.cart_quantity, name='cart_quantity'),

]

mealmate/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delivery/', include('delivery.urls')),
    path('',include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('handle_signup/', views.handle_signup, name="handle_signup"),
    path('handle_signin/', views.handle_signin, name='handle_signin'),
    path('cus_home/<str:username>', views.cus_home, name='cus_home'),
    path('admin_home/', views.admin_home, name='admin_home')
]

users/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=20)
    email = models.EmailField()
    mobile = models.CharField(max_length=12, default=90)
    address = models.CharField(max_length=100)
    role = models.CharField(max_length=10, default='CUSTOMER')

    def __str__(self):
        return f"{self.username}, {self.password}"

users/views.py
from django.shortcuts import render, redirect
from .models import Customer
from django.http import HttpResponse
from delivery.models import Restaurant

# Create your views here.
def index(request):
    return render(request,'users/sign_in.html')

def signin(request):
    return render(request,'users/sign_in.html')

def signup(request):
    return render(request,'users/sign_up.html')

def handle_signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        address = request.POST.get("address")
        role = request.POST.get("role")
        try:
            cus = Customer.objects.get(username=username)
            return render(request, 'users/sign_up.html', {'error': 'username already found'})
        except Customer.DoesNotExist:
            cus = Customer(username = username, password = password, email = email, mobile = mobile, address = address, role=role)
            cus.save()
        return render(request, 'users/sign_in.html')
    else:
        return HttpResponse("Invalid request")
        
def handle_signin(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print("Username:", username)   # Debug check
        print("Password:", password)  #Debug check
        
        cus = Customer.objects.filter(username=username, password=password).first()
        li = Restaurant.objects.all()

        if cus:
            if cus.role.lower() == 'vendor':
                return render(request, 'users/admin_home.html', {'li': li})
            else:
                print("Found customer:", cus)
                return render(request, 'users/cus_home.html', {'username': username, 'li': li})
        else:
            return render(request,'users/sign_in.html',{'error':'Invalid username or password'})

    else:
        return HttpResponse("Invalid Request")
    
def cus_home(request,username):
    li = Restaurant.objects.all()
    return render(request, 'users/cus_home.html', {'li':li, 'username': username})

def admin_home(request):
    li = Restaurant.objects.all()
    return render(request,'users/admin_home.html',{"li":li}) 

users/templates/users/admin_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Food Delivery</title>
    {% load static %}
<head>
    <link rel="stylesheet" href="{% static 'users/css/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
</head>
<body>

<nav>
    <h2>Food Delivery</h2>
    <div class="nav-links">
    <a href="{% url 'delivery:add_res' %}" class="nav-item" title="Add Restaurant">
        <i class="fas fa-store fa-lg"></i>
        <span>Add Res</span>
    </a>
    <a href="{% url 'delivery:add_menu' %}" class="nav-item" title="Add Menu">
        <i class="fas fa-utensils fa-lg"></i>
        <span>Add Menu</span>
    </a>
    <a href="{% url 'users:signin' %}" class="nav-item" title="Log Out">
        <i class="fas fa-sign-out-alt fa-lg"></i>
        <span>Logout</span>
    </a>
</div>
</nav>

<table border="1">
    <tr>
        <th>Restaurant Name:</th>
        <th>Category:</th>
        <th>Rating</th>
        <th>Image:</th>
        <th>Address</th>
        <th>View Menu</th>
    </tr>
    <tr>
        {% if li %}
        {% for item in li %}
        <td>{{item.res_name}}</td>
        <td>{{item.food_cat}}</td>
        <td>{{item.rating}}</td>
        <td><img src="{{item.img}}" alt="Restaurant Image"
             height="100" width="100" /></td>
        <td>{{item.address}}</td>
        <td>
            <a href="{% url "delivery:view_menu" item.id %}"><button>View Menu</button></a>
            <a href="{% url "delivery:edit_res" item.id %}"><button>Edit</button></a>
            <a href="{% url "delivery:delete_res" item.id %}"><button>Remove</button></a>
        </td>
    </tr>
        {% endfor %}
        
        {% else %}
        
        <a href="{% url "delivery:add_res" %}">Add Restaurant</a>
        
        {% endif %}
        
</table>


</body>
</html>

users/templates/users/cus_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Food Delivery</title>
    {% load static %}
<head>
    <link rel="stylesheet" href="{% static 'users/css/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
</head>
<body>

<nav>
    <h2>Food Delivery</h2>
    <div class="nav-links">
    <a href="{% url 'delivery:view_orders' username %}" class="nav-item" title="My Orders">
        <i class="fas fa-box fa-lg"></i>
        <span>Orders</span>
    </a>
    <a href="{% url 'delivery:view_cart' username %}" class="nav-item" title="View Cart">
        <i class="fas fa-shopping-cart fa-lg"></i>
        <span>Cart</span>
    </a>
    <a href="{% url 'users:signin' %}" class="nav-item" title="Log Out">
        <i class="fas fa-sign-out-alt fa-lg"></i>
        <span>Logout</span>
    </a>
</div>

</nav>

<h1>Hi {{username}}, Lets pick you favourite Restaurant</h1>
<div class="card-container">
    {% if li %}
    {% for item in li %}
    <div class="card">
        <img src="{{ item.img }}" alt="Restaurant Image">
        <div class="card-content">
            <h3>{{ item.res_name }}</h3>
            <p><strong>Category:</strong> {{ item.food_cat }}</p>
            <p><strong>Rating:</strong> {{ item.rating }}</p>
            <p><strong>Address:</strong> {{ item.address }}</p>
            <a href="{% url 'delivery:view_cusmenu' item.id username %}">
                <button>View Menu</button>
            </a>
        </div>
    </div>
    {% endfor %}
    
    
    {% else %}
    
    <h1 class="empty">No Restaurant Found</h1>
    
    
    
    {% endif %}
    
</div>


</body>
</html>

users/templates/users/sign_in.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>MealMate</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
</head>
<body>

<div class="form-box">
    <h1>SIGN IN</h1>

    {% if error %}
        <p>{{error}}</p>    
    {% endif %}

    <form method="POST" action="{% url 'users:handle_signin' %}">
        {% csrf_token %}

        <label>NAME:</label>
        <input type="text" name="username" required />

        <label>PASSWORD:</label>
        <input type="text" name="password" required />

        <button type="submit">SUBMIT</button>
    </form>

    <div class="signup-link">
        <a href="{% url 'users:signup' %}">New here? Sign Up</a>
    </div>
</div>

</body>
</html>

users/templates/users/sign_up.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>MealMate</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
</head>
<body>
    <div class="form-box">
        <h1>SIGN UP</h1>

        {% if error %}
         <p>{{error}}</p>    
        {% endif %}


        <form method="POST" action="{% url 'users:handle_signup' %}">
            {% csrf_token %}
            <label>NAME:</label>
            <input type="text" name="username" required />

            <label>PASSWORD:</label>
            <input type="text" name="password" required />

            <label>EMAIL:</label>
            <input type="email" name="email" required />

            <label>MOBILE:</label>
            <input type="tel" name="mobile" required />

            <label>ADDRESS:</label>
            <input type="text" name="address" required />

            <label for="role">ROLE: 
            <select name="role" id="role" required>
                <option value="customer" selected>Customer</option>
                <option value="vendor">Vendor</option>
            </select>
            </label>

            <button type="submit">SUBMIT</button>
        </form>
    

    <div class="signup-link">
        <a href="{% url 'users:signin' %}">already registered?Sign in</a>
    </div>
</div>
    
    
</body>
</html>